WebsiteThucPhamSach/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteThucPhamSach.Models;
namespace WebsiteThucPhamSach.Controllers
{
    public class FooterController : Controller
    {
        // GET: Footer
        QLTHUCPHAMEntities1 db = new QLTHUCPHAMEntities1();
        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }
        public string GetQC(int ThuTuQC)
        {
            var qc = db.QUANGCAOs.SingleOrDefault(n => n.THUTUQC == ThuTuQC && n.TRANGTHAI == true);
            string Anh = "";
            Anh += qc.ANHQC.ToString();
            return Anh;
        }
    }
}

WebsiteThucPhamSach/Controllers/NavbarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteThucPhamSach.Models;
namespace WebsiteThucPhamSach.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        QLTHUCPHAMEntities1 db = new QLTHUCPHAMEntities1();

        public PartialViewResult NavbarPartial()
        {
            string navbar = "";
            var Menu = (from p in db.MENUs select p).Where(p => p.TRANGTHAI == true).ToList();
            var danhmuc = (from c in db.DANHMUCs select c).Where(c => c.TRANGTHAI == true).ToList();
            int dem = 0;
            if (Menu.Count() > 0)
            {
                navbar += "<ul class='nav navbar-nav custom-nav-bg'>";
                for (int i = 0; i < Menu.Count(); i++)
                {
                    if(Menu[i].MAMN != danhmuc[dem].MAMN)
                    {
                        dem++;
                        navbar += "<li class='parent'><a class='child' href=" + Menu[i].HREF + " ref='nofollow'>" + Menu[i].TENMN + "</a></li>";
                    } 
                    else
                    {
                        if (danhmuc.Count() > 0)
                        {
                            navbar += "<li class='dropdown parent khung'><a class='dropdown-toggle child' data-toggle='dropdown' href='javascript:0'>" + Menu[i].TENMN + "<span class='caret tamgiac'></span></a>";
                            navbar += "<ul class='dropdown-menu kethua'>";
                            int MADM = 0;
                            for (int j = 0; j < danhmuc.Count(); j++)
                            {
                                MADM = danhmuc[j].MADM;
                                navbar += "<li><a href='San-Pham?MADM=" + MADM + "'>" + danhmuc[j].TENDM + "</a></li>";
                            }
                            navbar += "</ul>";
                            navbar += "</li>";
                        }
                    }
                }
                navbar += "</ul>";
            }
            ViewBag.Navbar = navbar;
            return PartialView();
        }
    }
}

WebsiteThucPhamSach/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Action("HeaderPartial", "Header")
    @Html.Action("NavbarPartial", "Navbar")
    <div class="body-content">
        @RenderBody()
    </div>
    <footer>
        @Html.Action("FooterPartial","Footer")
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.icon_user').click(function () {
                $('.login').toggleClass("hienthi");
            });
            $('.caret').click(function () {
                $('.information_login').toggleClass("hienthi");
            });
        });
    </script>
</body>
</html>